[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["datalib"]
package_dir = {"" = "src"}

[tool.setuptools.install_requires]
numpy
pandas
matplotlib
scikit-learn
