[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "datalib"
version = "0.1.0"
dependencies = [
    "numpy>=1.21",
    "pandas>=1.3",
    "matplotlib>=3.4",
    "scikit-learn>=0.24",
]

[tool.setuptools]
packages = ["datalib"]
package-dir = {"" = "src"}