[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["datalib"]
package_dir = {"" = "src"}

[options]
install_requires = [
    "numpy>=1.21",
    "pandas>=1.3",
    "matplotlib>=3.4",
    "scikit-learn>=0.24"
]