name: Python package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install seaborn  # Install seaborn explicitly
        pip install pytest  # Install pytest explicitly if not in requirements.txt

    - name: Run tests with PYTHONPATH
      run: |
        PYTHONPATH=src pytest  # Set PYTHONPATH directly for pytest
